-- Migration Script for Assistant Data
-- Generated by generate_assistant_migration.py
-- Handles auto-creation or lookup of 'Azusa' store
DO $$
DECLARE
    v_azusa_id BIGINT;
BEGIN
    -- Get or Create Azusa Store
    SELECT id INTO v_azusa_id FROM stores WHERE name = 'Azusa' LIMIT 1;
    IF v_azusa_id IS NULL THEN
        INSERT INTO stores (name, code, city) VALUES ('Azusa', 'AZ-001', 'Azusa') RETURNING id INTO v_azusa_id;
    END IF;


                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2025-12-26',
                    '20:51:00',
                    '20:54:00',
                    '{"refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "39\u00b0F", "refrig3_queso_cotija": "40\u00b0F", "refrig4_salsas": "39\u00b0F", "refrig5_salsas": "40\u00b0F", "walking": "40\u00b0F", "vapor1_lengua": "190\u00b0F", "vapor2_asada": "180\u00b0F", "vapor2_pastor": "183\u00b0F", "vapor3_chorizo": "162\u00b0F", "vapor3_salsa_huevo": "162\u00b0F", "vapor4_pollo": "188\u00b0F", "vapor4_buche": "180\u00b0F", "vapor5_arroz": "183\u00b0F", "vapor5_frijol": "179\u00b0F", "vapor6_asada": "178\u00b0F", "vapor7_chile_asado": "173\u00b0F", "vapor7_frijol_entero": "175\u00b0F"}',
                    100,
                    'Sensor de agua de la línea 1 se limpió ',
                    '26',
                    'Cruz Castillo',
                    '2025-12-26T20:51:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2025-12-26',
                    '23:53:00',
                    '23:55:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "NO", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "SI", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "NO", "food_handler": "NO", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    91,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-26T23:53:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2025-12-26',
                    '23:55:00',
                    '23:55:00',
                    '{"quitar_publicidad": "SI", "barrer_areas": "SI", "barrer_trapear_cocinas": "SI", "cambiar_bolsas": "SI", "limpieza_banos": "SI", "limpieza_parking": "SI", "horario_8_9am": "NA", "horario_1_2pm": "NA", "horario_3_4pm": "NA", "horario_6_7pm": "SI", "horario_10_11pm": "SI", "horario_1_2am": "SI", "horario_3_4am": "NA"}',
                    62,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-26T23:55:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    v_azusa_id,
                    'sobrante',
                    '2025-12-27',
                    '04:39:00',
                    '04:41:00',
                    '{"arroz": "2.12 lb", "frijol": "13.5 lb", "asada": "5.5 lb", "pastor": "3.14 lb", "pollo": "3.2 lb", "carnitas": "0.8 lb", "buche": "0.5 lb", "chorizo": "1.8 lb", "cabeza": "0 lb", "lengua": "1.8 lb", "frijoles_olla": "20.24 lb"}',
                    9,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-27T04:39:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'apertura',
                    '2025-12-27',
                    '13:21:00',
                    '13:21:00',
                    '{"desarmar_alarma": "SI", "encender_vaporeras": "SI", "encender_refrigeradores": "SI", "encender_planchas": "SI", "encender_luces": "SI", "encender_pantallas": "SI", "revision_areas": "SI", "recepcion_mercancias": "SI", "ordenar_mercancias": "SI", "limpieza_walking": "SI", "apertura_tiempo": "SI", "linea_produccion_abastecida": "SI", "apertura_cajas": "SI"}',
                    100,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-27T13:21:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2025-12-27',
                    '13:22:00',
                    '13:27:00',
                    '{"refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "40\u00b0F", "refrig3_queso_cotija": "41\u00b0F", "refrig4_salsas": "41\u00b0F", "refrig5_salsas": "41\u00b0F", "walking": "38\u00b0F", "vapor1_lengua": "195\u00b0F", "vapor2_asada": "186\u00b0F", "vapor2_pastor": "189\u00b0F", "vapor3_chorizo": "161\u00b0F", "vapor3_salsa_huevo": "165\u00b0F", "vapor4_pollo": "191\u00b0F", "vapor4_buche": "186\u00b0F", "vapor5_arroz": "186\u00b0F", "vapor5_frijol": "181\u00b0F", "vapor6_asada": "183\u00b0F", "vapor7_chile_asado": "170\u00b0F", "vapor7_frijol_entero": "171\u00b0F"}',
                    100,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-27T13:22:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2025-12-27',
                    '13:27:00',
                    '13:28:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "NO", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "SI", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "SI", "food_handler": "SI", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    97,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-27T13:27:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2025-12-27',
                    '22:24:00',
                    '22:25:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "floors_baseboards": "NO", "drains_clean": "SI", "ice_machine": "SI", "slicers_scissors": "SI", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "SI", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "NO", "food_handler": "NO", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    91,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-27T22:24:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2025-12-27',
                    '22:25:00',
                    '22:29:00',
                    '{"vapor7_frijol_entero": "189\u00b0F", "vapor7_chile_asado": "178\u00b0F", "vapor6_asada": "187\u00b0F", "vapor5_frijol": "180\u00b0F", "vapor5_arroz": "175\u00b0F", "vapor4_buche": "185\u00b0F", "vapor4_pollo": "189\u00b0F", "vapor3_salsa_huevo": "164\u00b0F", "vapor3_chorizo": "164\u00b0F", "vapor2_pastor": "178\u00b0F", "vapor2_asada": "183\u00b0F", "vapor1_lengua": "189\u00b0F", "walking": "39\u00b0F", "refrig5_salsas": "42\u00b0F", "refrig4_salsas": "42\u00b0F", "refrig3_queso_cotija": "39\u00b0F", "refrig2_carnes_cocinar": "41\u00b0F", "refrig1_quesadillas": "40\u00b0F"}',
                    89,
                    'Se le limpió el sensor de la línea 1 del llenado del agua ',
                    '26',
                    'Cruz Castillo',
                    '2025-12-27T22:25:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2025-12-27',
                    '22:29:00',
                    '22:29:00',
                    '{"quitar_publicidad": "SI", "barrer_areas": "SI", "barrer_trapear_cocinas": "SI", "cambiar_bolsas": "SI", "limpieza_banos": "SI", "limpieza_parking": "SI", "horario_8_9am": "NA", "horario_1_2pm": "NA", "horario_3_4pm": "NA", "horario_6_7pm": "SI", "horario_10_11pm": "SI", "horario_1_2am": "NA", "horario_3_4am": "NA"}',
                    62,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-27T22:29:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'apertura',
                    '2025-12-28',
                    '15:41:00',
                    '15:42:00',
                    '{"desarmar_alarma": "SI", "encender_vaporeras": "SI", "encender_refrigeradores": "SI", "encender_planchas": "SI", "encender_luces": "SI", "encender_pantallas": "SI", "revision_areas": "SI", "recepcion_mercancias": "SI", "ordenar_mercancias": "SI", "limpieza_walking": "SI", "apertura_tiempo": "SI", "linea_produccion_abastecida": "SI", "apertura_cajas": "SI"}',
                    100,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-28T15:41:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2025-12-28',
                    '15:42:00',
                    '15:43:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "SI", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "SI", "employee_bathroom": "NO", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "SI", "food_handler": "SI", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    97,
                    'Paredes de cámara fría se está despertando 
Baño de empleados está sucio el espejo',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-28T15:42:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2025-12-28',
                    '15:44:00',
                    '15:48:00',
                    '{"refrig1_quesadillas": "39\u00b0F", "refrig2_carnes_cocinar": "40\u00b0F", "refrig3_queso_cotija": "41\u00b0F", "refrig4_salsas": "41\u00b0F", "refrig5_salsas": "41\u00b0F", "walking": "39\u00b0F", "vapor1_lengua": "192\u00b0F", "vapor2_asada": "193\u00b0F", "vapor2_pastor": "190\u00b0F", "vapor3_chorizo": "164\u00b0F", "vapor3_salsa_huevo": "163\u00b0F", "vapor4_pollo": "191\u00b0F", "vapor4_buche": "190\u00b0F", "vapor5_arroz": "187\u00b0F", "vapor5_frijol": "184\u00b0F", "vapor6_asada": "191\u00b0F", "vapor7_chile_asado": "165\u00b0F", "vapor7_frijol_entero": "170\u00b0F"}',
                    100,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-28T15:44:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2025-12-28',
                    '15:48:00',
                    '15:49:00',
                    '{"quitar_publicidad": "SI", "barrer_areas": "SI", "barrer_trapear_cocinas": "SI", "cambiar_bolsas": "SI", "limpieza_banos": "SI", "limpieza_parking": "SI", "horario_8_9am": "SI", "horario_1_2pm": "SI", "horario_3_4pm": "SI", "horario_6_7pm": "NA", "horario_10_11pm": "NA", "horario_1_2am": "NA", "horario_3_4am": "NA"}',
                    69,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-28T15:48:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2025-12-28',
                    '22:19:00',
                    '22:20:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "NO", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "SI", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "NO", "food_handler": "NO", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    91,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-28T22:19:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2025-12-28',
                    '22:20:00',
                    '22:41:00',
                    '{"refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "39\u00b0F", "refrig3_queso_cotija": "40\u00b0F", "refrig4_salsas": "40\u00b0F", "refrig5_salsas": "41\u00b0F", "walking": "38\u00b0F", "vapor1_lengua": "193\u00b0F", "vapor2_asada": "189\u00b0F", "vapor2_pastor": "185\u00b0F", "vapor3_chorizo": "161\u00b0F", "vapor3_salsa_huevo": "161\u00b0F", "vapor4_pollo": "175\u00b0F", "vapor4_buche": "180\u00b0F", "vapor5_arroz": "182\u00b0F", "vapor5_frijol": "179\u00b0F", "vapor6_asada": "179\u00b0F", "vapor7_chile_asado": "170\u00b0F", "vapor7_frijol_entero": "172\u00b0F"}',
                    100,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-28T22:20:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2025-12-28',
                    '22:41:00',
                    '22:41:00',
                    '{"quitar_publicidad": "SI", "barrer_areas": "SI", "barrer_trapear_cocinas": "SI", "cambiar_bolsas": "SI", "limpieza_banos": "SI", "limpieza_parking": "SI", "horario_8_9am": "NA", "horario_1_2pm": "NA", "horario_3_4pm": "NA", "horario_6_7pm": "SI", "horario_10_11pm": "SI", "horario_3_4am": "NA", "horario_1_2am": "NA"}',
                    62,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-28T22:41:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'sobrante',
                    '2025-12-29',
                    '01:41:00',
                    '01:43:00',
                    '{"arroz": "0 lb", "frijol": "8.1 lb", "asada": "0 lb", "pastor": "1.9 lb", "pollo": "1.6 lb", "carnitas": "1.7 lb", "buche": "0.14 lb", "chorizo": "0.14 lb", "cabeza": "1.3 lb", "lengua": "0.15 lb", "frijoles_olla": "26.23 lb"}',
                    18,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-29T01:41:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'cierre',
                    '2025-12-29',
                    '02:10:00',
                    '02:11:00',
                    '{"cocina_contenedor_basura": "SI", "cocina_trapeadores": "SI", "cocina_contenedor_grasa": "SI", "cocina_trapos_agua_jabon": "SI", "cocina_cuarto_descanso": "SI", "cocina_refri_empleados": "SI", "cocina_bote_champurrado": "SI", "cocina_ollas_cafe": "SI", "planchas_apagadas_lavadas": "SI", "planchas_vaporera_tortillas": "SI", "cocina_vaporera_lavada": "SI", "cocina_olla_champurrado": "SI", "cocina_ollas_frijoles": "SI", "cocina_refrigerador_limpio": "SI", "cocina_barrida_trapeada": "SI", "cocina_coladeras_cloro": "SI", "cocina_charolas_rojas": "SI", "cocina_trastes_acomodados": "SI", "cocina_botes_basura": "SI", "cocina_productos_limpieza": "SI", "planchas_filtros_acido": "SI", "planchas_contenedores_grasa": "SI", "planchas_refri_planchas": "SI", "planchas_utencilios_acomodados": "SI", "planchas_charolas_grasa": "SI", "planchas_no_trapos_debajo": "SI", "planchas_productos_sobrantes": "SI", "vaporeras_limpias_apagadas": "SI", "vaporeras_trastes_acomodados": "SI", "vaporeras_basura_vacia": "SI", "vaporeras_refri_salsa_bar": "SI", "vaporeras_vidrios_limpios": "SI", "piso_linea_barrida_lavada": "SI", "piso_coladeras_cloro": "SI", "salon_area_cajas_limpia": "SI", "salon_basureros_limpios": "SI", "salon_banos_limpios": "SI", "salon_tvs_apagadas": "SI", "salon_botes_basura_vacios": "SI", "salon_puertas_cerradas": "SI", "salon_salon_limpio": "SI", "salon_luces_apagadas": "NO", "parking_barrido": "NO", "parking_candados_cerrados": "SI", "parking_contenedores_cerrados": "SI", "parking_basura_no_rebase": "SI"}',
                    96,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-29T02:10:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'apertura',
                    '2025-12-29',
                    '13:36:00',
                    '13:36:00',
                    '{"desarmar_alarma": "SI", "encender_vaporeras": "SI", "encender_refrigeradores": "SI", "encender_planchas": "SI", "encender_luces": "SI", "encender_pantallas": "SI", "revision_areas": "SI", "recepcion_mercancias": "SI", "ordenar_mercancias": "SI", "limpieza_walking": "SI", "apertura_tiempo": "SI", "linea_produccion_abastecida": "SI", "apertura_cajas": "SI"}',
                    100,
                    'Paredes de acero quirúrgico de cuarto frío se están desprendiendo  se necesita reforzarlos ',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-29T13:36:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2025-12-29',
                    '13:37:00',
                    '13:38:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "SI", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "NO", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "SI", "food_handler": "SI", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    97,
                    'Paredes de cama fría se están desprendiendo se necesita reforzar e 
Olla de preparación de champurrado está  su IA parte de atrás ',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-29T13:37:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2025-12-29',
                    '13:39:00',
                    '13:43:00',
                    '{"refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "39\u00b0F", "refrig3_queso_cotija": "41\u00b0F", "refrig4_salsas": "41\u00b0F", "refrig5_salsas": "40\u00b0F", "walking": "39\u00b0F", "vapor1_lengua": "190\u00b0F", "vapor2_asada": "188\u00b0F", "vapor2_pastor": "185\u00b0F", "vapor3_chorizo": "163\u00b0F", "vapor3_salsa_huevo": "170\u00b0F", "vapor4_pollo": "190\u00b0F", "vapor4_buche": "194\u00b0F", "vapor5_arroz": "176\u00b0F", "vapor5_frijol": "181\u00b0F", "vapor6_asada": "182\u00b0F", "vapor7_chile_asado": "170\u00b0F", "vapor7_frijol_entero": "175\u00b0F"}',
                    100,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-29T13:39:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2025-12-30',
                    '03:04:00',
                    '03:08:00',
                    '{"soda_co2": "SI", "repairs_reported": "SI", "cash_handling": "SI", "sos_dt_time": "SI", "mgmt_aware": "SI", "checklists_used": "SI", "food_handler": "NO", "cameras": "NO", "tables_chairs": "SI", "lighting": "SI", "tv_ac": "SI", "parking_lot": "NO", "bathrooms": "SI", "windows_clean": "SI", "eye_contact": "SI", "greeting_5sec": "SI", "soda_tank": "SI", "expediter": "SI", "towels_sanitizer": "SI", "fifo": "SI", "employee_bathroom": "SI", "champurrado": "SI", "broom_area": "SI", "handwashing": "SI", "microwave": "SI", "mop_sink": "NO", "floors_baseboards": "SI", "drains_clean": "SI", "ice_machine": "SI", "slicers_scissors": "SI", "sanitizer_bucket": "SI", "steel_clean": "SI", "lights_working": "SI", "temp_equipment": "SI"}',
                    88,
                    'Fuga de agua en el shing 
Fundida una lámpara de afuera ',
                    '26',
                    'Cruz Castillo',
                    '2025-12-30T03:04:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2025-12-30',
                    '03:08:00',
                    '03:14:00',
                    '{"vapor7_chile_asado": "172\u00b0F", "vapor7_frijol_entero": "170\u00b0F", "vapor6_asada": "184\u00b0F", "vapor5_frijol": "186\u00b0F", "vapor5_arroz": "191\u00b0F", "vapor4_pollo": "195\u00b0F", "vapor4_buche": "181\u00b0F", "vapor3_chorizo": "162\u00b0F", "vapor3_salsa_huevo": "162\u00b0F", "vapor2_asada": "190\u00b0F", "vapor2_pastor": "188\u00b0F", "vapor1_lengua": "188\u00b0F", "walking": "39\u00b0F", "refrig5_salsas": "41\u00b0F", "refrig4_salsas": "40\u00b0F", "refrig3_queso_cotija": "40\u00b0F", "refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "39\u00b0F"}',
                    100,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-30T03:08:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'sobrante',
                    '2025-12-30',
                    '03:14:00',
                    '03:16:00',
                    '{"arroz": "3.5 lb", "frijol": "0 lb", "asada": "1.4 lb", "pastor": "1.8 lb", "pollo": "3.3 lb", "carnitas": "0 lb", "buche": "1.3 lb", "chorizo": "0.13 lb", "cabeza": "1.1 lb", "lengua": "1.5 lb", "frijoles_olla": "4 lb"}',
                    18,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2025-12-30T03:14:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2025-12-30',
                    '03:18:00',
                    '03:19:00',
                    '{"quitar_publicidad": "SI", "barrer_areas": "SI", "barrer_trapear_cocinas": "SI", "cambiar_bolsas": "SI", "limpieza_banos": "SI", "limpieza_parking": "SI", "horario_8_9am": "NA", "horario_1_2pm": "NA", "horario_3_4pm": "NA", "horario_6_7pm": "SI", "horario_10_11pm": "SI", "horario_1_2am": "NA", "horario_3_4am": "NA"}',
                    62,
                    'Fuga de agua en el shing ',
                    '26',
                    'Cruz Castillo',
                    '2025-12-30T03:18:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'cierre',
                    '2025-12-30',
                    '03:19:00',
                    '03:21:00',
                    '{"cocina_vaporera_lavada": "SI", "cocina_olla_champurrado": "SI", "cocina_ollas_frijoles": "SI", "cocina_refrigerador_limpio": "SI", "cocina_barrida_trapeada": "SI", "cocina_coladeras_cloro": "SI", "cocina_charolas_rojas": "SI", "cocina_trastes_acomodados": "NO", "cocina_botes_basura": "SI", "cocina_trapeadores": "SI", "cocina_contenedor_grasa": "SI", "cocina_contenedor_basura": "SI", "parking_basura_no_rebase": "SI", "parking_contenedores_cerrados": "SI", "parking_barrido": "NO", "parking_candados_cerrados": "SI", "salon_luces_apagadas": "NO", "salon_salon_limpio": "SI", "salon_puertas_cerradas": "SI", "salon_tvs_apagadas": "SI", "salon_botes_basura_vacios": "SI", "salon_banos_limpios": "SI", "salon_basureros_limpios": "SI", "salon_area_cajas_limpia": "SI", "piso_coladeras_cloro": "SI", "piso_linea_barrida_lavada": "SI", "vaporeras_vidrios_limpios": "NO", "vaporeras_refri_salsa_bar": "SI", "vaporeras_basura_vacia": "SI", "vaporeras_trastes_acomodados": "NO", "vaporeras_limpias_apagadas": "SI", "planchas_productos_sobrantes": "SI", "planchas_no_trapos_debajo": "SI", "planchas_charolas_grasa": "SI", "planchas_utencilios_acomodados": "SI", "planchas_refri_planchas": "NO", "planchas_contenedores_grasa": "SI", "planchas_filtros_acido": "SI", "planchas_vaporera_tortillas": "SI", "planchas_apagadas_lavadas": "SI", "cocina_productos_limpieza": "SI", "cocina_ollas_cafe": "SI", "cocina_bote_champurrado": "SI", "cocina_refri_empleados": "SI", "cocina_cuarto_descanso": "SI", "cocina_trapos_agua_jabon": "SI"}',
                    87,
                    'Fuga de agua en el shing ',
                    '26',
                    'Cruz Castillo',
                    '2025-12-30T03:19:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'apertura',
                    '2025-12-30',
                    '14:43:00',
                    '14:43:00',
                    '{"desarmar_alarma": "SI", "encender_vaporeras": "SI", "encender_refrigeradores": "SI", "encender_planchas": "SI", "encender_luces": "SI", "encender_pantallas": "SI", "revision_areas": "SI", "recepcion_mercancias": "SI", "ordenar_mercancias": "SI", "limpieza_walking": "SI", "apertura_tiempo": "SI", "linea_produccion_abastecida": "SI", "apertura_cajas": "SI"}',
                    100,
                    'Fuga de agua abajo de Soc de lavatrastes',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-30T14:43:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2025-12-30',
                    '14:44:00',
                    '14:45:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "SI", "mop_sink": "NO", "microwave": "NO", "handwashing": "SI", "broom_area": "SI", "champurrado": "SI", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "SI", "food_handler": "SI", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    94,
                    'Fuga abajo del  zinc lava trastes',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-30T14:44:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2025-12-30',
                    '14:45:00',
                    '14:50:00',
                    '{"refrig1_quesadillas": "39\u00b0F", "refrig2_carnes_cocinar": "40\u00b0F", "refrig3_queso_cotija": "41\u00b0F", "refrig4_salsas": "41\u00b0F", "refrig5_salsas": "41\u00b0F", "walking": "39\u00b0F", "vapor1_lengua": "189\u00b0F", "vapor2_asada": "190\u00b0F", "vapor2_pastor": "187\u00b0F", "vapor3_chorizo": "172\u00b0F", "vapor3_salsa_huevo": "168\u00b0F", "vapor4_pollo": "190\u00b0F", "vapor4_buche": "189\u00b0F", "vapor5_arroz": "188\u00b0F", "vapor5_frijol": "170\u00b0F", "vapor6_asada": "190\u00b0F", "vapor7_chile_asado": "170\u00b0F", "vapor7_frijol_entero": "171\u00b0F"}',
                    100,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-30T14:45:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2025-12-30',
                    '17:20:00',
                    '17:22:00',
                    '{"quitar_publicidad": "SI", "barrer_areas": "SI", "barrer_trapear_cocinas": "SI", "cambiar_bolsas": "SI", "limpieza_banos": "SI", "limpieza_parking": "NO", "horario_8_9am": "SI", "horario_1_2pm": "SI", "horario_3_4pm": "SI", "horario_6_7pm": "NA", "horario_10_11pm": "NA", "horario_1_2am": "NA", "horario_3_4am": "NA"}',
                    62,
                    'Olla de champurrado continúa la falla 
Área de despacho de hielo en el salón ya quedó pero estuvo fallando 
Fuga de agua de bajo del sino ya quedó 
Pte el recorrido sólo el estacionamiento',
                    '27',
                    'Enrique Navarrete',
                    '2025-12-30T17:20:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'apertura',
                    '2026-01-01',
                    '16:29:00',
                    '16:30:00',
                    '{"desarmar_alarma": "SI", "encender_vaporeras": "SI", "encender_refrigeradores": "SI", "encender_planchas": "SI", "encender_luces": "SI", "encender_pantallas": "SI", "revision_areas": "SI", "recepcion_mercancias": "SI", "ordenar_mercancias": "SI", "apertura_tiempo": "SI", "limpieza_walking": "SI", "linea_produccion_abastecida": "SI", "apertura_cajas": "SI"}',
                    100,
                    'Se encontró encendido el congelador de. Cocina dos 
',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-01T16:29:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2026-01-01',
                    '16:30:00',
                    '16:35:00',
                    '{"refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "39\u00b0F", "refrig3_queso_cotija": "41\u00b0F", "refrig4_salsas": "40\u00b0F", "refrig5_salsas": "40\u00b0F", "walking": "40\u00b0F", "vapor1_lengua": "195\u00b0F", "vapor2_asada": "197\u00b0F", "vapor2_pastor": "190\u00b0F", "vapor3_chorizo": "164\u00b0F", "vapor3_salsa_huevo": "163\u00b0F", "vapor4_pollo": "199\u00b0F", "vapor4_buche": "194\u00b0F", "vapor5_arroz": "187\u00b0F", "vapor5_frijol": "189\u00b0F", "vapor6_asada": "184\u00b0F", "vapor7_chile_asado": "176\u00b0F", "vapor7_frijol_entero": "178\u00b0F"}',
                    100,
                    'Continúa paredes de wualking desprendiéndose ',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-01T16:30:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2026-01-01',
                    '16:36:00',
                    '16:36:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "SI", "mop_sink": "NO", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "NO", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "SI", "food_handler": "SI", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    94,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-01T16:36:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2026-01-01',
                    '17:07:00',
                    '17:08:00',
                    '{"quitar_publicidad": "SI", "barrer_areas": "SI", "barrer_trapear_cocinas": "SI", "cambiar_bolsas": "SI", "limpieza_banos": "SI", "limpieza_parking": "SI", "horario_8_9am": "SI", "horario_1_2pm": "NA", "horario_3_4pm": "NA", "horario_6_7pm": "NA", "horario_10_11pm": "NA", "horario_1_2am": "NA", "horario_3_4am": "NA"}',
                    54,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-01T17:07:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2026-01-02',
                    '02:33:00',
                    '02:34:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "NO", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "SI", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "NO", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "NO", "food_handler": "NO", "checklists_used": "SI", "mgmt_aware": "SI", "soda_co2": "SI", "repairs_reported": "SI", "cash_handling": "SI", "sos_dt_time": "SI"}',
                    88,
                    'Lámpara fundida ',
                    '26',
                    'Cruz Castillo',
                    '2026-01-02T02:33:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2026-01-02',
                    '02:35:00',
                    '02:37:00',
                    '{"refrig1_quesadillas": "41\u00b0F", "refrig2_carnes_cocinar": "39\u00b0F", "refrig3_queso_cotija": "40\u00b0F", "refrig4_salsas": "40\u00b0F", "refrig5_salsas": "40\u00b0F", "walking": "40\u00b0F", "vapor1_lengua": "199\u00b0F", "vapor2_asada": "200\u00b0F", "vapor2_pastor": "191\u00b0F", "vapor3_chorizo": "162\u00b0F", "vapor3_salsa_huevo": "162\u00b0F", "vapor4_pollo": "199\u00b0F", "vapor4_buche": "195\u00b0F", "vapor5_arroz": "186\u00b0F", "vapor5_frijol": "191\u00b0F", "vapor6_asada": "185\u00b0F", "vapor7_chile_asado": "190\u00b0F", "vapor7_frijol_entero": "180\u00b0F"}',
                    100,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-02T02:35:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'sobrante',
                    '2026-01-02',
                    '02:37:00',
                    '02:38:00',
                    '{"arroz": "0 lb", "frijol": "0 lb", "asada": "0 lb", "pastor": "0 lb", "pollo": "0 lb", "carnitas": "0.6 lb", "buche": "1.2 lb", "chorizo": "0.10 lb", "cabeza": "0.14 lb", "lengua": "1 lb", "frijoles_olla": "20.7 lb"}',
                    45,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-02T02:37:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2026-01-02',
                    '02:38:00',
                    '02:39:00',
                    '{"horario_3_4am": "NA", "horario_1_2am": "NO", "horario_10_11pm": "SI", "horario_6_7pm": "SI", "horario_3_4pm": "NA", "horario_1_2pm": "NA", "horario_8_9am": "NA", "limpieza_parking": "SI", "limpieza_banos": "SI", "cambiar_bolsas": "SI", "barrer_trapear_cocinas": "SI", "barrer_areas": "SI", "quitar_publicidad": "SI"}',
                    62,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-02T02:38:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'cierre',
                    '2026-01-02',
                    '03:09:00',
                    '03:12:00',
                    '{"cocina_vaporera_lavada": "SI", "cocina_olla_champurrado": "SI", "cocina_ollas_frijoles": "SI", "cocina_refrigerador_limpio": "SI", "cocina_barrida_trapeada": "SI", "cocina_coladeras_cloro": "SI", "cocina_charolas_rojas": "SI", "cocina_trastes_acomodados": "SI", "cocina_botes_basura": "SI", "cocina_trapeadores": "SI", "cocina_contenedor_grasa": "SI", "cocina_contenedor_basura": "SI", "cocina_trapos_agua_jabon": "SI", "cocina_cuarto_descanso": "SI", "cocina_refri_empleados": "SI", "cocina_bote_champurrado": "SI", "cocina_ollas_cafe": "SI", "cocina_productos_limpieza": "SI", "planchas_apagadas_lavadas": "SI", "planchas_vaporera_tortillas": "SI", "planchas_filtros_acido": "SI", "planchas_contenedores_grasa": "SI", "planchas_refri_planchas": "NO", "planchas_utencilios_acomodados": "SI", "planchas_charolas_grasa": "SI", "planchas_no_trapos_debajo": "SI", "planchas_productos_sobrantes": "SI", "vaporeras_limpias_apagadas": "SI", "vaporeras_trastes_acomodados": "SI", "vaporeras_refri_salsa_bar": "SI", "vaporeras_basura_vacia": "SI", "vaporeras_vidrios_limpios": "NO", "piso_linea_barrida_lavada": "SI", "piso_coladeras_cloro": "SI", "salon_area_cajas_limpia": "SI", "salon_basureros_limpios": "SI", "salon_banos_limpios": "SI", "salon_botes_basura_vacios": "SI", "salon_tvs_apagadas": "SI", "salon_puertas_cerradas": "SI", "salon_luces_apagadas": "NO", "salon_salon_limpio": "SI", "parking_barrido": "NO", "parking_candados_cerrados": "SI", "parking_contenedores_cerrados": "SI", "parking_basura_no_rebase": "SI"}',
                    91,
                    'Fuga de agua en la linia de enfrente ',
                    '26',
                    'Cruz Castillo',
                    '2026-01-02T03:09:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'apertura',
                    '2026-01-02',
                    '10:44:00',
                    '10:46:00',
                    '{"desarmar_alarma": "SI", "encender_vaporeras": "SI", "encender_refrigeradores": "SI", "encender_planchas": "SI", "encender_luces": "SI", "encender_pantallas": "SI", "revision_areas": "SI", "recepcion_mercancias": "SI", "ordenar_mercancias": "SI", "limpieza_walking": "SI", "apertura_tiempo": "SI", "linea_produccion_abastecida": "NO", "apertura_cajas": "SI"}',
                    92,
                    'Continúa la pared despegándose de la cámara fría 
Líneas  de salón faltando de abastecerse ',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-02T10:44:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2026-01-02',
                    '10:46:00',
                    '10:50:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "NO", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "NO", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "SI", "food_handler": "SI", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    94,
                    'Paredes de cámara fría continúa desprendiéndose 
Máquina de agua  de cocina dos no enfrían bien 
',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-02T10:46:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2026-01-02',
                    '10:51:00',
                    '10:58:00',
                    '{"refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "40\u00b0F", "refrig3_queso_cotija": "40\u00b0F", "refrig4_salsas": "41\u00b0F", "refrig5_salsas": "41\u00b0F", "walking": "41\u00b0F", "vapor1_lengua": "199\u00b0F", "vapor2_asada": "195\u00b0F", "vapor2_pastor": "187\u00b0F", "vapor3_chorizo": "163\u00b0F", "vapor3_salsa_huevo": "165\u00b0F", "vapor4_pollo": "191\u00b0F", "vapor4_buche": "195\u00b0F", "vapor5_arroz": "184\u00b0F", "vapor5_frijol": "186\u00b0F", "vapor6_asada": "189\u00b0F", "vapor7_chile_asado": "170\u00b0F", "vapor7_frijol_entero": "171\u00b0F"}',
                    100,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-02T10:51:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2026-01-02',
                    '21:03:00',
                    '21:04:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "NO", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "SI", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "NO", "parking_lot": "NO", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "NO", "food_handler": "NO", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    85,
                    'Fuga de agua en la línea de enfrente ',
                    '26',
                    'Cruz Castillo',
                    '2026-01-02T21:03:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2026-01-02',
                    '21:04:00',
                    '21:09:00',
                    '{"refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "38\u00b0F", "refrig3_queso_cotija": "40\u00b0F", "refrig4_salsas": "40\u00b0F", "refrig5_salsas": "40\u00b0F", "walking": "39\u00b0F", "vapor1_lengua": "190\u00b0F", "vapor2_asada": "182\u00b0F", "vapor2_pastor": "180\u00b0F", "vapor3_chorizo": "161\u00b0F", "vapor3_salsa_huevo": "161\u00b0F", "vapor4_pollo": "185\u00b0F", "vapor4_buche": "182\u00b0F", "vapor5_arroz": "180\u00b0F", "vapor5_frijol": "181\u00b0F", "vapor6_asada": "185\u00b0F", "vapor7_chile_asado": "176\u00b0F", "vapor7_frijol_entero": "170\u00b0F"}',
                    100,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-02T21:04:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2026-01-02',
                    '21:09:00',
                    '21:09:00',
                    '{"quitar_publicidad": "SI", "barrer_areas": "SI", "barrer_trapear_cocinas": "SI", "cambiar_bolsas": "SI", "limpieza_banos": "SI", "limpieza_parking": "SI", "horario_8_9am": "NA", "horario_1_2pm": "NA", "horario_3_4pm": "NA", "horario_6_7pm": "SI", "horario_10_11pm": "NA", "horario_1_2am": "NA", "horario_3_4am": "NA"}',
                    54,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-02T21:09:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'sobrante',
                    '2026-01-03',
                    '04:00:00',
                    '04:07:00',
                    '{"arroz": "4 lb", "frijol": "0 lb", "asada": "0 lb", "pastor": "1.10 lb", "pollo": "0 lb", "carnitas": "0 lb", "buche": "0 lb", "chorizo": "1.3 lb", "cabeza": "0 lb", "lengua": "3 lb", "frijoles_olla": "18.8 lb"}',
                    55,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-03T04:00:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'cierre',
                    '2026-01-03',
                    '04:07:00',
                    '04:08:00',
                    '{"cocina_vaporera_lavada": "SI", "cocina_olla_champurrado": "SI", "cocina_ollas_frijoles": "SI", "cocina_refrigerador_limpio": "SI", "cocina_barrida_trapeada": "SI", "cocina_coladeras_cloro": "SI", "cocina_charolas_rojas": "SI", "cocina_trastes_acomodados": "SI", "cocina_botes_basura": "SI", "cocina_trapeadores": "SI", "cocina_contenedor_grasa": "SI", "cocina_contenedor_basura": "SI", "cocina_trapos_agua_jabon": "SI", "cocina_cuarto_descanso": "SI", "cocina_refri_empleados": "SI", "cocina_bote_champurrado": "SI", "cocina_ollas_cafe": "SI", "cocina_productos_limpieza": "SI", "planchas_apagadas_lavadas": "SI", "planchas_vaporera_tortillas": "SI", "planchas_filtros_acido": "SI", "planchas_contenedores_grasa": "SI", "planchas_refri_planchas": "NO", "planchas_utencilios_acomodados": "SI", "planchas_charolas_grasa": "SI", "planchas_no_trapos_debajo": "SI", "planchas_productos_sobrantes": "SI", "vaporeras_limpias_apagadas": "SI", "vaporeras_trastes_acomodados": "SI", "vaporeras_basura_vacia": "SI", "vaporeras_refri_salsa_bar": "SI", "vaporeras_vidrios_limpios": "NO", "piso_linea_barrida_lavada": "SI", "piso_coladeras_cloro": "SI", "salon_area_cajas_limpia": "SI", "salon_basureros_limpios": "SI", "salon_banos_limpios": "SI", "salon_botes_basura_vacios": "SI", "salon_tvs_apagadas": "SI", "salon_puertas_cerradas": "SI", "salon_salon_limpio": "SI", "salon_luces_apagadas": "NO", "parking_barrido": "NO", "parking_candados_cerrados": "SI", "parking_contenedores_cerrados": "SI", "parking_basura_no_rebase": "NO"}',
                    89,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-03T04:07:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'apertura',
                    '2026-01-03',
                    '13:13:00',
                    '13:15:00',
                    '{"desarmar_alarma": "SI", "encender_vaporeras": "SI", "encender_refrigeradores": "SI", "encender_planchas": "SI", "encender_luces": "SI", "encender_pantallas": "SI", "revision_areas": "SI", "recepcion_mercancias": "SI", "ordenar_mercancias": "SI", "limpieza_walking": "SI", "apertura_tiempo": "SI", "linea_produccion_abastecida": "SI", "apertura_cajas": "SI"}',
                    100,
                    'Pared de cámara fría se está desprendiendo
',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-03T13:13:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2026-01-03',
                    '13:16:00',
                    '13:23:00',
                    '{"refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "40\u00b0F", "refrig3_queso_cotija": "41\u00b0F", "refrig4_salsas": "40\u00b0F", "refrig5_salsas": "41\u00b0F", "walking": "42\u00b0F", "vapor1_lengua": "197\u00b0F", "vapor2_asada": "189\u00b0F", "vapor2_pastor": "190\u00b0F", "vapor3_chorizo": "168\u00b0F", "vapor3_salsa_huevo": "163\u00b0F", "vapor4_pollo": "185\u00b0F", "vapor4_buche": "187\u00b0F", "vapor5_arroz": "188\u00b0F", "vapor5_frijol": "186\u00b0F", "vapor6_asada": "195\u00b0F", "vapor7_chile_asado": "162\u00b0F", "vapor7_frijol_entero": "171\u00b0F"}',
                    94,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-03T13:16:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2026-01-03',
                    '13:23:00',
                    '13:24:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "SI", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "NO", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "SI", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "SI", "food_handler": "SI", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    97,
                    'Párese de cama fría despegándose ',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-03T13:23:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2026-01-03',
                    '23:50:00',
                    '23:51:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "NO", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "NO", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "NO", "parking_lot": "NO", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "food_handler": "NO", "cameras": "NO", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    82,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-03T23:50:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'temperaturas',
                    '2026-01-03',
                    '23:51:00',
                    '23:54:00',
                    '{"refrig1_quesadillas": "40\u00b0F", "refrig2_carnes_cocinar": "40\u00b0F", "refrig3_queso_cotija": "40\u00b0F", "refrig4_salsas": "40\u00b0F", "refrig5_salsas": "40\u00b0F", "walking": "39\u00b0F", "vapor1_lengua": "199\u00b0F", "vapor2_asada": "182\u00b0F", "vapor2_pastor": "181\u00b0F", "vapor3_chorizo": "170\u00b0F", "vapor3_salsa_huevo": "170\u00b0F", "vapor4_pollo": "190\u00b0F", "vapor4_buche": "184\u00b0F", "vapor5_arroz": "187\u00b0F", "vapor5_frijol": "183\u00b0F", "vapor6_asada": "186\u00b0F", "vapor7_chile_asado": "170\u00b0F", "vapor7_frijol_entero": "174\u00b0F"}',
                    100,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-03T23:51:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'recorrido',
                    '2026-01-03',
                    '23:54:00',
                    '23:54:00',
                    '{"quitar_publicidad": "SI", "barrer_areas": "SI", "barrer_trapear_cocinas": "SI", "cambiar_bolsas": "SI", "limpieza_banos": "SI", "limpieza_parking": "NO", "horario_8_9am": "NA", "horario_1_2pm": "NA", "horario_3_4pm": "NA", "horario_6_7pm": "SI", "horario_10_11pm": "SI", "horario_1_2am": "SI", "horario_3_4am": "NA"}',
                    62,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-03T23:54:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'sobrante',
                    '2026-01-04',
                    '03:12:00',
                    '03:13:00',
                    '{"arroz": "2 lb", "frijol": "7.3 lb", "asada": "0.13 lb", "pastor": "2.1 lb", "pollo": "0.14 lb", "carnitas": "1.12 lb", "buche": "0 lb", "chorizo": "1.13 lb", "cabeza": "1.3 lb", "lengua": "1.2 lb", "frijoles_olla": "13.16 lb"}',
                    9,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-04T03:12:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'cierre',
                    '2026-01-04',
                    '04:03:00',
                    '04:05:00',
                    '{"cocina_contenedor_grasa": "SI", "cocina_trapeadores": "SI", "cocina_botes_basura": "SI", "cocina_trastes_acomodados": "SI", "cocina_charolas_rojas": "SI", "cocina_coladeras_cloro": "SI", "cocina_barrida_trapeada": "SI", "cocina_refrigerador_limpio": "SI", "cocina_ollas_frijoles": "SI", "cocina_olla_champurrado": "SI", "cocina_vaporera_lavada": "SI", "cocina_contenedor_basura": "SI", "cocina_trapos_agua_jabon": "SI", "cocina_cuarto_descanso": "SI", "cocina_refri_empleados": "SI", "cocina_bote_champurrado": "SI", "cocina_ollas_cafe": "SI", "planchas_vaporera_tortillas": "SI", "planchas_filtros_acido": "SI", "planchas_contenedores_grasa": "SI", "planchas_refri_planchas": "SI", "planchas_utencilios_acomodados": "SI", "planchas_charolas_grasa": "SI", "planchas_no_trapos_debajo": "SI", "planchas_productos_sobrantes": "SI", "vaporeras_limpias_apagadas": "SI", "vaporeras_trastes_acomodados": "SI", "vaporeras_basura_vacia": "SI", "vaporeras_refri_salsa_bar": "SI", "vaporeras_vidrios_limpios": "NO", "piso_linea_barrida_lavada": "SI", "piso_coladeras_cloro": "SI", "salon_area_cajas_limpia": "SI", "salon_basureros_limpios": "SI", "salon_banos_limpios": "SI", "salon_botes_basura_vacios": "SI", "salon_tvs_apagadas": "SI", "parking_basura_no_rebase": "SI", "parking_contenedores_cerrados": "SI", "parking_candados_cerrados": "SI", "parking_barrido": "SI", "salon_luces_apagadas": "NO", "salon_salon_limpio": "SI", "salon_puertas_cerradas": "SI", "planchas_apagadas_lavadas": "SI", "cocina_productos_limpieza": "SI"}',
                    96,
                    '',
                    '26',
                    'Cruz Castillo',
                    '2026-01-04T04:03:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'apertura',
                    '2026-01-04',
                    '15:46:00',
                    '15:47:00',
                    '{"desarmar_alarma": "SI", "encender_vaporeras": "SI", "encender_refrigeradores": "SI", "encender_planchas": "SI", "encender_luces": "SI", "encender_pantallas": "SI", "revision_areas": "SI", "recepcion_mercancias": "SI", "ordenar_mercancias": "SI", "limpieza_walking": "SI", "apertura_tiempo": "SI", "linea_produccion_abastecida": "SI", "apertura_cajas": "SI"}',
                    100,
                    '',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-04T15:46:00'
                );
                
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    14,
                    'daily',
                    '2026-01-04',
                    '15:47:00',
                    '15:49:00',
                    '{"temp_equipment": "SI", "lights_working": "SI", "steel_clean": "SI", "sanitizer_bucket": "SI", "slicers_scissors": "SI", "ice_machine": "SI", "drains_clean": "SI", "floors_baseboards": "SI", "mop_sink": "SI", "microwave": "SI", "handwashing": "SI", "broom_area": "SI", "champurrado": "SI", "employee_bathroom": "SI", "fifo": "SI", "towels_sanitizer": "SI", "expediter": "SI", "soda_tank": "SI", "greeting_5sec": "SI", "eye_contact": "SI", "windows_clean": "SI", "bathrooms": "SI", "parking_lot": "NO", "tv_ac": "SI", "lighting": "SI", "tables_chairs": "SI", "cameras": "SI", "food_handler": "SI", "checklists_used": "SI", "mgmt_aware": "SI", "sos_dt_time": "SI", "cash_handling": "SI", "repairs_reported": "SI", "soda_co2": "SI"}',
                    97,
                    'Estacionamiento sucio por la lluvia  limpiándose más tarde',
                    '27',
                    'Enrique Navarrete',
                    '2026-01-04T15:47:00'
                );
                END $$;
