import csv
import json
import datetime

# Configuration
LEGACY_CSV = 'asistentes.csv'
SUPABASE_CSV = 'assistant_checklists_rows.csv'
OUTPUT_SQL = 'migrate_assistant_final.sql'

# Known IDs - we will stick with these for existing ones
STORE_MAP = {
    'Bell': 15,
    'Lynwood': 14,
    'Downey': 13,
    'South Gate': 16,
}

TYPE_MAP = {
    'inspeccion_apertura': 'apertura',
    'inspeccion_cierre': 'cierre',
    'producto_sobrante': 'sobrante',
    'temperaturas': 'temperaturas',
    'daily': 'daily',
    'recorrido': 'recorrido'
}

def escape_sql(value):
    if value is None:
        return 'NULL'
    if isinstance(value, str):
        return "'" + value.replace("'", "''") + "'"
    return str(value)

def main():
    # 1. Build User Map from Supabase Data
    user_map = {}
    print(f"Loading users from {SUPABASE_CSV}...")
    try:
        with open(SUPABASE_CSV, 'r', encoding='utf-8') as f:
            reader = csv.DictReader(f)
            for row in reader:
                uid = row.get('user_id')
                uname = row.get('user_name')
                if uid and uname:
                    user_map[uname] = uid
    except Exception as e:
        print(f"Warning mapping users: {e}")

    # 2. Process Legacy Data
    print(f"Processing {LEGACY_CSV}...")
    try:
        with open(LEGACY_CSV, 'r', encoding='utf-8') as f_in, \
             open(OUTPUT_SQL, 'w', encoding='utf-8') as f_out:
            
            reader = csv.DictReader(f_in)
            
            f_out.write("-- Migration Script for Assistant Data\n")
            f_out.write("-- Generated by generate_assistant_migration.py\n")
            f_out.write("-- Handles auto-creation or lookup of 'Azusa' store\n")
            f_out.write("-- Includes 'shift' mapping\n")
            
            # Start DO block to allow variables
            f_out.write("DO $$\n")
            f_out.write("DECLARE\n")
            f_out.write("    v_azusa_id BIGINT;\n")
            f_out.write("BEGIN\n")
            
            # Lookup or Create Azusa Store
            f_out.write("    -- Get or Create Azusa Store\n")
            f_out.write("    SELECT id INTO v_azusa_id FROM stores WHERE name = 'Azusa' LIMIT 1;\n")
            f_out.write("    IF v_azusa_id IS NULL THEN\n")
            f_out.write("        INSERT INTO stores (name, code, city) VALUES ('Azusa', 'AZ-001', 'Azusa') RETURNING id INTO v_azusa_id;\n")
            f_out.write("    END IF;\n\n")
            
            count = 0
            skipped = 0
            
            for row in reader:
                # Store Mapping
                store_name = row.get('store', '').strip()
                
                # Determine how to reference the store ID
                if store_name == 'Azusa':
                    store_id_sql = 'v_azusa_id'
                else:
                    store_id = STORE_MAP.get(store_name)
                    if not store_id:
                        print(f"Skipping row {count+skipped}: Unknown store '{store_name}'")
                        skipped += 1
                        continue
                    store_id_sql = str(store_id)
                
                # User Mapping
                user_name = row.get('user', '').strip()
                user_id = user_map.get(user_name)
                
                # Checklist Type Mapping
                c_type_raw = row.get('checklist_type', '').strip()
                c_type = TYPE_MAP.get(c_type_raw, c_type_raw)
                
                # Date Processing
                start_ts_str = row.get('start_time', '').strip()
                end_ts_str = row.get('end_time', '').strip()
                
                checklist_date = 'NULL'
                start_time_sql = 'NULL'
                end_time_sql = 'NULL'
                created_at_sql = 'NOW()'
                
                try:
                    if start_ts_str:
                        try:
                            dt = datetime.datetime.strptime(start_ts_str, '%m/%d/%Y %H:%M')
                        except ValueError:
                            dt = datetime.datetime.strptime(start_ts_str, '%m/%d/%Y %H:%M')
                        
                        checklist_date = f"'{dt.date()}'"
                        start_time_sql = f"'{dt.time()}'"
                        created_at_sql = f"'{dt.isoformat()}'"
                    
                    if end_ts_str:
                        dt_end = datetime.datetime.strptime(end_ts_str, '%m/%d/%Y %H:%M')
                        end_time_sql = f"'{dt_end.time()}'"
                except:
                    skipped += 1
                    continue
                
                # SHIFT Mapping
                shift_val = row.get('shift', '')
                if not shift_val:
                    shift_sql = 'NULL'
                else:
                    # Escape or validate? It's typically AM/PM. 
                    # If it's empty in CSV, it will be NULL.
                    # If it's valid, map it.
                    shift_sql = escape_sql(shift_val)

                # JSON Answers
                answers_str = row.get('answers_json', '{}')
                try:
                    answers_json = json.loads(answers_str)
                    answers_val = escape_sql(json.dumps(answers_json))
                except:
                    answers_val = "'{}'"
                
                # Score & Comments
                score = row.get('score', 0)
                if not score: score = 0
                
                comments = escape_sql(row.get('comments', ''))
                
                u_id_val = f"'{user_id}'" if user_id else 'NULL'
                u_name_val = escape_sql(user_name)
                
                sql = f"""
                INSERT INTO assistant_checklists (
                    store_id,
                    checklist_type,
                    checklist_date,
                    start_time,
                    end_time,
                    shift,
                    answers,
                    score,
                    comments,
                    user_id,
                    user_name,
                    created_at
                ) VALUES (
                    {store_id_sql},
                    '{c_type}',
                    {checklist_date},
                    {start_time_sql},
                    {end_time_sql},
                    {shift_sql},
                    {answers_val},
                    {score},
                    {comments},
                    {u_id_val},
                    {u_name_val},
                    {created_at_sql}
                );
                """
                f_out.write(sql)
                count += 1
            
            f_out.write("END $$;\n") # End DO block
            
            print(f"Successfully generated SQL for {count} records.")
            print(f"Output saved to {OUTPUT_SQL}")

    except FileNotFoundError:
        print(f"Error: {LEGACY_CSV} not found.")

if __name__ == '__main__':
    main()
