
CREATE TABLE IF NOT EXISTS operating_procedures (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    start_time TIME,
    duration_minutes NUMERIC,
    activity TEXT NOT NULL,
    shift_type TEXT NOT NULL,
    frequency TEXT NOT NULL,
    role TEXT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE operating_procedures ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON operating_procedures;
CREATE POLICY "Enable read access for all users" ON operating_procedures FOR SELECT USING (true);

TRUNCATE TABLE operating_procedures;

INSERT INTO operating_procedures (start_time, duration_minutes, activity, shift_type, frequency, role, description)
VALUES
('08:00:00', 2, 'Abrir puerta y desactivar alarma', 'Apertura', 'Diario', 'Asistente/SL', NULL),
('08:02:00', 1, 'Encender luces de cocina', 'Apertura', 'Diario', 'Asistente/SL', NULL),
('08:02:00', 60, 'Lavar freidoras', 'Apertura', 'Viernes', 'Asistente/SL', NULL),
('08:02:00', 30, 'Revisar y limpiar ROOF', 'Apertura', 'Domingo', 'Asistente/SL', NULL),
('08:03:00', 15, 'Preparar las cajas registradoras', 'Apertura', 'Diario', 'Asistente/SL', NULL),
('08:18:00', 20, 'Lavar filtros de campanas y colocarlos', 'Apertura', 'Diario', 'Asistente/SL', NULL),
('08:40:00', 30, 'Armar y rellenar maquinas de aguas, mover tapetes y mapear', 'Apertura', 'Diario', 'Asistente/SL', NULL),
('08:50:00', 10, 'Limpieza de vidrios de toda la linea (incluido salsabar)', 'Apertura', 'Diario', 'Asistente/SL', NULL),
('09:00:00', 60, 'Recepcion, revision y acomodamiento de la mercancia', 'Apertura', 'Diario', NULL, NULL),
('09:00:00', 1, 'Encender Steamer', 'Apertura', 'Diario', NULL, NULL),
('09:00:00', 10, 'Preparacion de frijol molido y de la olla', 'Apertura', 'Diario', NULL, NULL),
('09:10:00', 10, 'Acomodar los tapetes (lavados de anoche)', 'Apertura', 'Lunes', NULL, NULL),
('09:10:00', 10, 'Rellenar arroz, cabeza y lengua en el steamer', 'Apertura', 'Diario', NULL, NULL),
('09:20:00', 10, 'Rellenar salsa bar (limones, salsar, cebolla, chiles, frijoles)', 'Apertura', 'Diario', NULL, NULL),
('09:00:00', 30, 'Rellenar refrigeradores de la linea (carnes, tortillas, jamon, salchicha, milaneza, huevos, papelitos, quesadillas, mulitas, burritos, nachos, sopes, teleras)', 'Apertura', 'Diario', NULL, NULL),
('09:30:00', 15, 'Rellenar steam table (frijol, arroz, cebolla, quesos, salsas verde y roja, crema, aguacate, mayo, aluminio)', 'Apertura', 'Diario', NULL, NULL),
('09:30:00', 20, 'Preparacion de champurrado', 'Apertura', 'Diario', NULL, NULL),
('09:45:00', 15, 'Revision de salon y baños', 'Apertura', 'Diario', NULL, NULL),
('09:50:00', 5, 'Preparacion de salsa ranchera', 'Apertura', 'Diario', NULL, NULL),
('09:30:00', 1, 'Encender planchas', 'Apertura', 'Diario', NULL, NULL),
('09:30:00', 1, 'Encender freidora', 'Apertura', 'Diario', NULL, NULL),
('09:30:00', 1, 'Encender campanas y sus luces', 'Apertura', 'Diario', NULL, NULL),
('09:30:00', 1, 'Encender Steam table (llenado de agua y calentamiento)', 'Apertura', 'Diario', NULL, NULL),
('09:35:00', 5, 'Colocar cubetas rojas de sanitizer', 'Apertura', 'Diario', NULL, NULL),
('09:40:00', 5, 'Colocar toallas (trapos) en la linea, cajas y preparacion', 'Apertura', 'Diario', NULL, NULL),
('09:40:00', 20, 'Preparacion de guacamole, cremas y mayonesa', 'Apertura', 'Diario', NULL, NULL),
('09:45:00', 7.5, 'Cocinar asada en plancha grande', 'Apertura', 'Diario', 'La carne asada se expande completamente en los 450° y se deja ahi sin moverla entre 2 a 2 ½ min, despues se junta y se le da vuelta y se deja otros 2 min. al terminar este tiempo se avienta hacia la derecha a los 300° para reposarla un minuto y luego se voltea para otro minuto, en total 2 min. Siempre verificar el reloj de pared', NULL),
('09:45:00', 8, 'Cocinar Pollo en plancha pequeña', 'Apertura', 'Diario', 'El pollo se expande completamente en los 450° y se deja ahi sin moverla entre 3 a 3½ min, despues se junta y se le da vuelta y se deja otros 2 min. al terminar este tiempo se avienta hacia la derecha a los 300° para reposarla un minuto y luego se voltea para otro minuto, en total 2 min. Siempre verificar el reloj de pared', NULL),
('09:50:00', 5, 'Cocinar tostadas', 'Apertura', 'Diario', 'El pastor se expande completamente en los 450° y se deja ahi sin moverla 2 min, despues se avienta hacia la derecha para raspar y limpiar el adobo pegado, se regresa a los 450° otros 2 min. al terminar este tiempo se avienta hacia la derecha a los 300° para reposarla un minuto y luego se voltea para otro minuto, en total 2 min. Siempre verificar el reloj de pared', NULL),
('09:53:00', 7.5, 'Cocinar Pastor en plancha grande', 'Apertura', 'Diario', 'La Cebolla se expande en los 450° y se deja sin moverla 1 minuto, despues se voltea y se deja 1 minuto mas.', NULL),
('09:53:00', 2, 'Cocinar cebollas asadas', 'Apertura', 'Diario', NULL, NULL),
('09:55:00', 2, 'Encender TVs', 'Apertura', 'Diario', NULL, NULL),
('09:57:00', 1, 'Encender luces del comedor', 'Apertura', 'Diario', NULL, NULL),
('10:00:00', 1, 'Abrir la puerta principal a los clientes', 'Apertura', 'Diario', NULL, NULL),
('10:00:00', 3, 'Abrir Drive Thru', 'Apertura', 'Diario', NULL, NULL),
('10:00:00', 20, 'Limpieza del walking (limpiar, barrer y mapear)', 'Apertura', 'Diario', NULL, NULL),
('10:00:00', 20, 'Barrer y mop cocina y linea de preparacion', 'Regular', 'Diario', NULL, NULL),
('10:00:00', 2, 'Colocar charolas rojas de entrega de ordenes en la linea', 'Apertura', 'Diario', NULL, NULL),
('10:00:00', 60, 'Barrer y mapear comedor de clientes', 'Regular', 'Diario', NULL, NULL),
('10:01:00', 5, 'Rellenar refrigerador de postres y botellas de agua', 'Regular', 'Diario', NULL, NULL),
('10:30:00', 5, 'Rellenar cucharas, tenedores, cuchillos, vasos, servilletas, popotes, palillos, cremas, azucar, sal', 'Apertura', 'Diario', NULL, NULL),
('11:00:00', 20, 'Tomar temperaturas y daily Check', 'Regular', 'Diario', NULL, NULL),
('11:00:00', 30, 'Barrer parking', 'Regular', 'Diario', NULL, NULL),
('13:00:00', 5, 'CASH DROP', 'Regular', 'Diario', NULL, NULL),
('15:00:00', 60, 'Barrer y mapear comedor de clientes', 'Regular', 'Diario', NULL, NULL),
('16:00:00', 5, 'CASH DROP', 'Regular', 'Diario', NULL, NULL),
('16:00:00', 20, 'Limpieza general de baños', 'Regular', 'Diario', NULL, NULL),
('16:30:00', 20, 'Tirar basura al contenedor externo', 'Regular', 'Diario', NULL, NULL),
('17:00:00', 10, 'Cambio de turno', 'Regular', 'Diario', NULL, NULL),
('17:50:00', 20, 'Tomar temperaturas y daily Check', 'Regular', 'Diario', NULL, NULL),
('19:00:00', 5, 'CASH DROP', 'Regular', 'Diario', NULL, NULL),
('21:00:00', 5, 'CASH DROP', 'Regular', 'Diario', NULL, NULL),
('23:00:00', 5, 'CASH DROP', 'Regular', 'Diario', NULL, NULL),
('23:00:00', 20, 'Limpieza general de baños', 'Regular', 'Diario', NULL, NULL),
('23:30:00', 20, 'Tirar basura al contenedor externo', 'Regular', 'Diario', NULL, NULL),
('00:00:00', 30, 'AVANZAR LINEA (lavar steam table burritos)', 'Cierre', 'Diario', NULL, NULL),
('00:30:00', 20, 'LAVAR PLANCHA GRANDE', 'Cierre', 'Diario', NULL, NULL),
('00:50:00', 5, 'LAVAR PLANCHA DE BURRITOS', 'Cierre', 'DOMINGO', NULL, NULL),
('01:00:00', 20, 'Lavar tapetes negros (salon y baños)', 'Cierre', 'Domingo', NULL, NULL),
('01:00:00', 60, 'PROFUNDO bajar filtros (acido), limpieza campana y paredes de acero inox, debajo de planchas, cajones de refrigeradores, abajo de steamtable, panera', 'Cierre', 'Jueves y Domingo', NULL, NULL),
('01:00:00', 20, 'Lavado de maquina de sodas', 'Cierre', 'Diario', NULL, NULL),
('01:00:00', 10, 'LAVAR VAPORERA (TORTILLAS)', 'Cierre', 'Diario', NULL, NULL),
('01:00:00', 50, 'LAVAR TRASTES Y ACOMODARLOS', 'Cierre', 'Diario', NULL, NULL),
('01:00:00', 30, 'LAVAR LINEA Y SALSABAR', 'Cierre', 'Diario', NULL, NULL),
('01:00:00', 30, 'LAVADA PROFUNDA VAPORERA DE TORTILLAS', 'Cierre', 'JUEVES', NULL, NULL),
('01:00:00', 15, 'CIERRE SALON, CAFETERAS, MAQUINA DE SODAS Y BAñOS', 'Cierre', 'Diario', NULL, NULL),
('01:00:00', 2, 'APAGAR TVS', 'Cierre', 'Diario', NULL, NULL),
('01:00:00', 30, 'CORTES Y DEPOSITO', 'Cierre', 'Diario', NULL, NULL),
('01:00:00', 20, 'CONTAR SOBRANTES Y MARCAR, CONTAR FLANES Y CK', 'Cierre', 'Diario', NULL, NULL),
('01:20:00', 10, 'ENVIAR LA ORDEN A LA BODEGA', 'Cierre', 'Diario', NULL, NULL),
('01:10:00', 15, 'LAVAR PLANCHA TORTAS', 'Cierre', 'Diario', NULL, NULL),
('01:25:00', 20, 'SACAR BASURAS y cambiar bolsas', 'Cierre', 'Diario', NULL, NULL),
('01:30:00', 15, 'LAVAR PISOS Y ACOMODAR TRASTES', 'Cierre', 'Diario', NULL, NULL),
('01:30:00', NULL, 'LAVAR PANERA (SHELF)', 'Cierre', 'JUEVES', NULL, NULL),
('01:40:00', 20, 'PESAR CARNES', 'Cierre', 'Diario', NULL, NULL),
('01:45:00', 15, 'LAVAR TODOS LOS BAñOS', 'Cierre', 'Diario', NULL, NULL),
('01:45:00', 15, 'LAVAR BOTES BASURA Y CAJONERAS ACERO INOX', 'Cierre', 'Diario', NULL, NULL),
('01:50:00', 10, 'Limpieza de vidrios de toda la linea (incluido salsabar)', 'Cierre', 'Diario', NULL, NULL),
('02:00:00', 2, 'APAGAR LUCES SALON, COCINA', 'Cierre', 'Diario', NULL, NULL),
('02:00:00', 1, 'ARMAR ALARMA', 'Cierre', 'Diario', NULL, NULL),
('02:00:00', 3, 'CHECKLIST CIERRE', 'Cierre', 'Diario', NULL, NULL),
('02:00:00', NULL, 'REVISAR BOTES DE CUARTO DE BASURA TAPAS CERRADAS', 'Cierre', 'Diario', NULL, NULL),
('22:30:00', 15, 'Lavar plancha chica', 'Cierre', 'Diario', NULL, NULL),
('22:30:00', NULL, 'LAVAR COLADERAS Y AVANZAR TRASTES', 'Cierre', 'Diario', NULL, NULL),
('23:40:00', 20, 'BAJAR FILTROS Y APAGAR PLANCHA DE BURRITOS', 'Cierre', 'Diario', NULL, NULL),
('23:40:00', 20, 'LAVAR FILTROS Y LIMPIAR CAMPANA Y PARED', 'Cierre', 'Diario', NULL, NULL);
